/*1*/
select * from CAULACBO
select * from CAUTHU

select CAULACBO.MACLB, COUNT(CAULACBO.MACLB) as N'Số lượng cầu thủ' from CAULACBO
inner join CAUTHU on CAULACBO.MACLB = CAUTHU.MACLB
group by CAULACBO.MACLB

/*2*/
select CAULACBO.TENCLB ,COUNT(*) as N'Số cầu thủ ngoại' from CAUTHU
inner join CAULACBO on CAUTHU.MACLB = CAULACBO.MACLB
where CAUTHU.MAQG not like 'VN'
group by CAULACBO.TENCLB

/*3*/
select CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI, COUNT(CAULACBO.MACLB) as N'Số cầu thủ ngoại' from CAUTHU
inner join CAULACBO on CAUTHU.MACLB = CAULACBO.MACLB
inner join SANVD on CAULACBO.MASAN = SANVD.MASAN
where CAUTHU.MAQG not like 'VN'
group by CAULACBO.MACLB, CAULACBO.TENCLB, SANVD.TENSAN, SANVD.DIACHI
having COUNT(CAULACBO.MACLB) > 2

select * from CAUTHU

/*4*/
select TINH.TENTINH, COUNT(TINH.TENTINH) as N'Số lượng cầu thủ tiền đạo' from CAUTHU
inner join CAULACBO on CAULACBO.MACLB = CAUTHU.MACLB
inner join TINH on CAULACBO.MATINH = TINH.MATINH
where CAUTHU.VITRI = N'Tiền Đạo'
group by TINH.TENTINH

/*5*/
select  TOP(1) CAULACBO.TENCLB, TINH.TENTINH, BANGXH.DIEM from CAULACBO
inner join TINH on CAULACBO.MATINH = TINH.MATINH
inner join BANGXH on CAULACBO.MACLB = BANGXH.MACLB
where VONG = 3 and NAM = 2009 
group by CAULACBO.TENCLB, TINH.TENTINH, BANGXH.DIEM

