
/*1*/
select COUNT(*) from HUANLUYENVIEN, HLV_CLB
WHERE HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV AND HUANLUYENVIEN.DIENTHOAI IS NULL

/*2*/
select * from HUANLUYENVIEN
LEFT JOIN HLV_CLB ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
where HLV_CLB.MAHLV is null

/*3*/
select CAUTHU.* from CAUTHU 
inner join CAULACBO on CAUTHU.MACLB = CAULACBO.MACLB
inner join BANGXH on CAULACBO.MACLB = BANGXH.MACLB
where BANGXH.VONG = 3 and BANGXH.NAM = 2009 and BANGXH.HANG between 3 and 6

/*4*/
select top(1) TRANDAU.NGAYTD, c1.TENCLB, c2.TENCLB, SANVD.TENSAN, TRANDAU.KETQUA from TRANDAU 
inner join CAULACBO as c1 on TRANDAU.MACLB1 = c1.MACLB
inner join CAULACBO as c2 on TRANDAU.MACLB2 = c2.MACLB
inner join BANGXH on c1.MACLB = BANGXH.MACLB
inner join SANVD on TRANDAU.MASAN = SANVD.MASAN
where BANGXH.VONG = 3 and BANGXH.NAM = 2009
order by BANGXH.DIEM desc
