select * from CAUTHU
/*2*/
select * from CAUTHU
where VITRI = N'Tiền vệ'AND SO = 7

/*4*/
select SC.* from CAUTHU AS SC, QUOCGIA AS N, CAULACBO AS FC
where sc.MACLB = fc.MACLB and sc.MAQG = n.MAQG
and n.TENQG = N'Việt Nam' and fc.TENCLB = N'Becamex Bình Dương'

select * from CAUTHU AS SC, QUOCGIA AS N, CAULACBO AS FC
where sc.MACLB = fc.MACLB and sc.MAQG = n.MAQG

/*6*/
select * from CAUTHU
INNER JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
INNER JOIN TINH ON CAULACBO.MATINH = TINH.MATINH
WHERE TINH.TENTINH = N'LONG AN'

/*7*/
select TRANDAU.* from TRANDAU
inner join CAULACBO AS C1 ON TRANDAU.MACLB1 = C1.MACLB
inner join CAULACBO AS C2 on TRANDAU.MACLB2 = C2.MACLB
where TRANDAU.NAM = 2009 and TRANDAU.VONG = 2
go

select * from TRANDAU

/*8*/
select HUANLUYENVIEN.*, CAULACBO.TENCLB, HLV_CLB.VAITRO from HUANLUYENVIEN
inner join QUOCGIA on HUANLUYENVIEN.MAQG = QUOCGIA.MAQG
inner join HLV_CLB on HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
inner join CAULACBO on HLV_CLB.MACLB = CAULACBO.MACLB
where QUOCGIA.TENQG = N'Việt Nam'

/*9*/
select TOP(3)* from CAULACBO, BANGXH
where CAULACBO.MACLB = BANGXH.MACLB
and BANGXH.VONG = 3  and BANGXH.NAM = 2009
order by BANGXH.DIEM desc

/*10*/
select HUANLUYENVIEN.MAHLV, HUANLUYENVIEN.TENHLV,HUANLUYENVIEN.NGAYSINH ,HUANLUYENVIEN.DIACHI, HLV_CLB.VAITRO, CAULACBO.TENCLB  from HUANLUYENVIEN
inner join HLV_CLB on HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
inner join CAULACBO on HLV_CLB.MACLB = CAULACBO.MACLB
inner join TINH on CAULACBO.MATINH = TINH.MATINH
where TINH.TENTINH = N'Bình Dương'

select * from HUANLUYENVIEN